### PR TITLE
Use base images in ghcr.io

### PR DESCRIPTION
**Pull request by imjasonh**
https://github.com/shipwright-io/build/issues/913

See image: https://ghcr.io/shipwright-io/shipwright-samples/maven:3-jdk-8-openj9

### CODE REVIEW

**Review by otaviof — APPROVED** [review]
/lgtm

**Comment by HeavyWombat** [comment]
@imjasonh @otaviof Could one you double check, I seem to have problems loading one of the images.
```
$ docker pull ghcr.io/shipwright-io/shipwright-samples/open-liberty:kernel-java8-openj9-ubi
Trying to pull ghcr.io/shipwright-io/shipwright-samples/open-liberty:kernel-java8-openj9-ubi...
Error: initializing source docker://ghcr.io/shipwright-io/shipwright-samples/open-liberty:kernel-java8-openj9-ubi: Requesting bear token: invalid status code from registry 403 (Forbidden)
$
$ docker pull ghcr.io/shipwright-io/shipwright-samples/maven:3-jdk-8-openj9
Trying to pull ghcr.io/shipwright-io/shipwright-samples/maven:3-jdk-8-openj9...
Getting image source signatures
Copying blob sha256:909a719c4fc9c8057c7861bc21bd325734c7e91b67420cbbfcd4cc1844b58ce8
Copying blob sha256:b2655016a42840bf8171f4406893502d4cff560556a7981cfd76a1ea8c173ed1
Copying blob sha256:1a53b0e22d89318528cb8a8ba36ca421ed699c31cb6b12e2f6a9b77b10f935e7
Copying blob sha256:706b9b9c1c443d1cd3d83fa6ecf9e3a4ae13b711dcc6b3aa34e9603c1cb8a930
Copying blob sha256:bd80ccc25e1d772d0d295b7d162e54c2e861748dd2bff2dadf930cede52046e6
Copying blob sha256:f3ef4ff62e0da0ef761ec1c8a578f3035bef51043e53ae1b13a20b3e03726d17
Copying blob sha256:b2655016a42840bf8171f4406893502d4cff560556a7981cfd76a1ea8c173ed1
Copying blob sha256:f3ef4ff62e0da0ef761ec1c8a578f3035bef51043e53ae1b13a20b3e03726d17
Copying blob sha256:1a53b0e22d89318528cb8a8ba36ca421ed699c31cb6b12e2f6a9b77b10f935e7
Copying blob sha256:65686c11d81c4d8799c5c61f5738d69b4a9cf78666b400e304e16c393470c631
Copying blob sha256:706b9b9c1c443d1cd3d83fa6ecf9e3a4ae13b711dcc6b3aa34e9603c1cb8a930
Copying blob sha256:909a719c4fc9c8057c7861bc21bd325734c7e91b67420cbbfcd4cc1844b58ce8
Copying blob sha256:bd80ccc25e1d772d0d295b7d162e54c2e861748dd2bff2dadf930cede52046e6
Copying blob sha256:65686c11d81c4d8799c5c61f5738d69b4a9cf78666b400e304e16c393470c631
Copying config sha256:60b3a60b2f6f32ddfb70cc936212ec8be0d3f964226ecbb8991e8210ed110684
Writing manifest to image destination
Storing signatures
60b3a60b2f6f32ddfb70cc936212ec8be0d3f964226ecbb8991e8210ed110684
```

**Comment by imjasonh** [comment]
After https://github.com/shipwright-io/build/pull/932 and https://github.com/shipwright-io/build/runs/4081946229?check_suite_focus=true the image should be there now:

```
$ docker pull ghcr.io/shipwright-io/shipwright-samples/open-liberty:kernel-java8-openj9-ubi
kernel-java8-openj9-ubi: Pulling from shipwright-io/shipwright-samples/open-liberty
ec1681b6a383: Downloading [=========================>                         ]  37.84MB/73.86MB
c4d668e229cd: Download complete 
ab5c4f4bffe6: Download complete 
5fb7bfe3044f: Download complete 
371fe28dd907: Download complete 
8844ac3b8359: Download complete 
f44d037b7eb6: Download complete 
f87b15f2bf73: Download complete 
64dfa9407640: Download complete 
d8b93da6f830: Downloading [============>                                      ]  42.71MB/175.4MB
5d5b852ec707: Download complete 
7205b542686c: Download complete 
d16ad2a56062: Download complete 
```

**Review by SaschaSchwarze0 — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
